# Generated by Django 3.0 on 2019-12-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0003_auto_20191216_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitnadv',
            name='time_start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mitnadv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='snif',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
