# Generated by Django 3.0 on 2019-12-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0004_auto_20191216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitnadv',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
