# Generated by Django 3.0 on 2019-12-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0005_auto_20191216_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitnadv',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
