# Generated by Django 3.0 on 2019-12-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0007_mitnadv_time_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayForMounthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
