# Generated by Django 3.0 on 2019-12-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0008_payformounthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='payformounthmodel',
            name='pay_m',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mit_app.Mitnadv'),
        ),
        migrations.AddField(
            model_name='payformounthmodel',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
