# Generated by Django 3.0 on 2019-12-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0009_auto_20191218_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payformounthmodel',
            old_name='pay_m',
            new_name='to',
        ),
    ]
