# Generated by Django 3.0 on 2019-12-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0010_auto_20191218_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitnadv',
            old_name='money_m',
            new_name='money_for_month',
        ),
    ]
