# Generated by Django 3.0 on 2019-12-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_app', '0013_auto_20191219_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
